[package]
name = "newsapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.3.1"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.71"
thiserror = "1.0.30"